Create test_steps.md
JJK3-org/Review_request pull request #3
Opened 2021-07-30 12:09 UTC by jjkennedy3

going to dismiss this with branch protections

2021-07-30 12:09 UTC, jjkenn-1 approved these changes
approved

2021-07-30 12:12 UTC, jjkenn-1 reviewed
approved

2021-07-30 12:14 UTC, jjkenn-1 commented on test_steps.md
> + - record results (should be listed as approve in PR)
change this line

2021-07-30 12:14 UTC, jjkenn-1 commented on test_steps.md
> + - _Results:_ showed as approved in PR
comment

2021-07-30 12:15 UTC, jjkenn-1 approved these changes

2021-07-30 12:15 UTC, jjkenn-1 commented on test_steps.md
> +6. push a commit to fork
comment then approve

2021-07-30 12:20 UTC, jjkenn-1 requested changes

2021-07-30 12:20 UTC, jjkenn-1 commented on test_steps.md
> + - Review results (dismiss review, change entry, etc)
request change

2021-07-30 13:48 UTC, jjkennedy3 commented
`test comment`

2021-07-31 18:48 UTC, jjkenn-1 approved these changes
approve after commit but before push

2021-08-09 15:23 UTC, jjkenn-1 approved these changes

2021-08-09 15:24 UTC, merged